// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace OWASP.WebGoat.NET {
	
	
	public partial class ChangePassword {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl lblHeader;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.ChangePassword ChangePwdCtrl;
		
		protected System.Web.UI.WebControls.TextBox CurrentPassword;
		
		protected System.Web.UI.WebControls.TextBox NewPassword;
		
		protected System.Web.UI.WebControls.TextBox ConfirmNewPassword;
		
		protected System.Web.UI.WebControls.Button ChangePasswordPushButton;
		
		protected System.Web.UI.WebControls.Button CancelPushButton;
		
		protected System.Web.UI.WebControls.Literal FailureText;
		
		protected System.Web.UI.WebControls.Button ContinuePushButton;
	}
}
