// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace OWASP.WebGoat.NET {
	
	
	public partial class LoginPage {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl lblHeader;
		
		protected System.Web.UI.WebControls.Content Content3;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.Literal labelMessage;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtUserName;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtPassword;
		
		protected System.Web.UI.HtmlControls.HtmlInputCheckBox checkBoxRemember;
		
		protected System.Web.UI.WebControls.Button buttonLogOn;
	}
}
