// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace OWASP.WebGoat.NET.resources.Master_Pages {
	
	
	public partial class Site {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder HeadContentPlaceHolder;
		
		protected System.Web.UI.HtmlControls.HtmlForm Form1;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor A1;
		
		protected System.Web.UI.WebControls.LoginView HeadLoginView;
		
		protected System.Web.UI.WebControls.LoginName HeadLoginName;
		
		protected System.Web.UI.WebControls.LinkButton lbtGenerateTestData;
		
		protected System.Web.UI.WebControls.LoginStatus HeadLoginStatus;
		
		protected System.Web.UI.WebControls.SiteMapDataSource SiteMapDataSource1;
		
		protected System.Web.UI.WebControls.Repeater rptrMenu;
		
		protected System.Web.UI.WebControls.Repeater rptrSubmenu;
		
		protected System.Web.UI.WebControls.SiteMapPath SiteMapPath1;
		
		protected System.Web.UI.WebControls.Literal ltlMessage;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder HelpContentPlaceholder;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder BodyContentPlaceholder;
	}
}
