// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace OWASP.WebGoat.NET.Content {
	
	
	public partial class Random {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.Label lblSequence;
		
		protected System.Web.UI.WebControls.Button btnOneMore;
		
		protected System.Web.UI.WebControls.Button btnReset;
		
		protected System.Web.UI.WebControls.TextBox txtNextNumber;
		
		protected System.Web.UI.WebControls.Button btnGo;
		
		protected System.Web.UI.WebControls.Label lblResult;
		
		protected System.Web.UI.WebControls.Content Content3;
	}
}
