// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Web;
using System.Web.UI;

namespace OWASP.WebGoat.NET
{
    public partial class RegexDoS
    {
        protected System.Web.UI.WebControls.Content Content1;
        
        protected System.Web.UI.WebControls.Content Content2;
        
        protected System.Web.UI.WebControls.Label lblError;
        
        protected System.Web.UI.WebControls.TextBox txtUsername;

        protected System.Web.UI.WebControls.TextBox txtPassword;
        
        protected System.Web.UI.WebControls.Button btnUpload;
    }
}

