// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace OWASP.WebGoat.NET {
	
	
	public partial class SQLInjectionDiscovery {
		
		protected System.Web.UI.WebControls.Content Content3;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.TextBox txtID;
		
		protected System.Web.UI.WebControls.Button btnFind;
		
		protected System.Web.UI.WebControls.GridView grdEmail;
		
		protected System.Web.UI.WebControls.Label lblOutput;
	}
}
