// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace OWASP.WebGoat.NET {
	
	
	public partial class StoredXSS {
		
		protected System.Web.UI.WebControls.Content Content3;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.Label lblOutput;
		
		protected System.Web.UI.WebControls.Label lblMessage;
		
		protected System.Web.UI.WebControls.Label lblComments;
		
		protected System.Web.UI.WebControls.Table Table1;
		
		protected System.Web.UI.WebControls.TableRow TableRow1;
		
		protected System.Web.UI.WebControls.TableCell TableCell1;
		
		protected System.Web.UI.WebControls.TableCell TableCell2;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.TableRow TableRow2;
		
		protected System.Web.UI.WebControls.TableCell TableCell3;
		
		protected System.Web.UI.WebControls.TableCell TableCell4;
		
		protected System.Web.UI.WebControls.TextBox txtComment;
		
		protected System.Web.UI.WebControls.TableRow TableRow3;
		
		protected System.Web.UI.WebControls.TableCell TableCell5;
		
		protected System.Web.UI.WebControls.TableCell TableCell6;
		
		protected System.Web.UI.WebControls.Button btnSave;
	}
}
