// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace OWASP.WebGoat.NET.WebGoatCoins {
	
	
	public partial class CustomerLogin {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.Content Content3;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divNotice;
		
		protected System.Web.UI.WebControls.Literal labelMessage;
		
		protected System.Web.UI.WebControls.Panel PanelError;
		
		protected System.Web.UI.WebControls.Literal labelError;
		
		protected System.Web.UI.WebControls.TextBox txtUserName;
		
		protected System.Web.UI.WebControls.TextBox txtPassword;
		
		protected System.Web.UI.HtmlControls.HtmlInputCheckBox checkBoxRemember;
		
		protected System.Web.UI.WebControls.Button buttonLogOn;
	}
}
