// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace OWASP.WebGoat.NET.WebGoatCoins {
	
	
	public partial class Orders {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.Content Content3;
		
		protected System.Web.UI.WebControls.Literal labelMessage;
		
		protected System.Web.UI.WebControls.Label lblOutput;
		
		protected System.Web.UI.WebControls.GridView GridView1;
		
		protected System.Web.UI.WebControls.Panel PanelShowDetailSuccess;
		
		protected System.Web.UI.WebControls.Literal litSuccessDetailMessage;
		
		protected System.Web.UI.WebControls.Panel PanelShowDetailFailure;
		
		protected System.Web.UI.WebControls.Literal litErrorDetailMessage;
		
		protected System.Web.UI.WebControls.Panel PanelShowDetails;
		
		protected System.Web.UI.WebControls.DetailsView DetailsView1;
		
		protected System.Web.UI.WebControls.HyperLink HyperLink1;
	}
}
